# Generated by Django 5.0.4 on 2024-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaitapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
