# Generated by Django 5.0.4 on 2024-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedaitapp', '0002_rename_contact_teacher_contact_alter_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
