# Generated by Django 5.0.4 on 2024-05-26 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0008_rename_users_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="SAUser",
        ),
    ]
