# Generated by Django 5.0.4 on 2024-05-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0009_rename_user_sauser"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Customer", models.CharField(max_length=50)),
                ("Firstname", models.CharField(max_length=50)),
                ("Lastname", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("Contact", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="SAUser",
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vedaitapp.user",
            ),
        ),
    ]
