# Generated by Django 5.0.4 on 2024-05-29 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0011_users_alter_customer_user_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
    ]
