# Generated by Django 5.0.4 on 2024-05-29 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0012_rename_product_orderitem_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
