# Generated by Django 5.0.4 on 2024-05-29 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0013_rename_qunatity_orderitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="qunatity",
        ),
    ]
