# Generated by Django 5.0.4 on 2024-06-09 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vedaitapp", "0014_rename_quantity_orderitem_qunatity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
